# Hugoのブログのテーマ3つ用意: ["hugo-tranquilpeak-theme", "", ""]
theme = "hugo-tranquilpeak-theme"

# information
title = "日々のできごとを思うがままに"
baseURL = "https://yumatsuoka.github.io/blog"
languageCode = "us-en"
defaultContentLanguage = "ja"
hasCJKLanguage = true
googleAnalytics = "UA-112843722-2"
paginate = 5
publishDir = "docs"
enableRobotsTXT = true #imperfect
canonifyURLs = true


[permalinks]
	post = "/:year/:month/:day/:filename/"

[taxonomies]
    tag = "tags" #tranquilpeak
    category = "categories" #tranquilpeak
    archive = "archives" #tranquilpeak

[author] #tranquilpeak
	name = "yumatsuoka"
    bio = "ボルチモアのジョンズホプキンス大学に留学中。ボルダリングやロープクライミングにはまっています。" #tranquilpeak
    job = "学生"
    location = "Baltimore, US" #tranquilpeak
	#email = "a.iebako.yuma@gmail.com"
    picture = "https://farm5.staticflickr.com/4786/39803594885_c76f9290a3_z.jpg"
	
[params]
    author = "Yuma Matsuoka" 
	brand = "yumatsuoka"
	topline = "日々のできごとを思うがままに"
	footline = "Copyright&copy; <a href='/about/'>yumatsuoka</a>"
    keywords = ["ボルチモア", "クライミング"] #tranquilpeak
    syntaxHighlighter = "highlight.js" #tranquilpeak
    clearReading = true #tranquilpeak
    hierarchicalCategories = false #tranquilpeak
    description = "ボルチモアのジョンズホプキンス大学で研究しつつ、クライミングやボルダリングをする日々" #tranquilpeak
    sidebarBehavior = 1 #tranquilpeak これがサイドバーのレイアウトを変えるフラグ1から6まで。
    coverImage = "cover.jpg" #tranquilpeak googlephotoなどクラウド上にあげられる場合はurl, またはローカル
    imageGallery = true #tranquilpeak
    thumbnailImage = true #tranquilpeak
    thumbnailImagePosition = "bottom" #tranquilpeak
    autoThumbnailImage = true #tranquilpeak

    [[params.sharingOptions]]
        name = "Facebook"
        icon = "fa-facebook-official"
        url = "https://www.facebook.com/sharer/sharer.php?u=%s"

    [[params.sharingOptions]]
        name = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/intent/tweet?text=%s"

    [[params.sharingOptions]]
        name = "Google+"
        icon = "fa-google-plus"
        url = "https://plus.google.com/share?url=%s"

    [params.header.rightLink]
        class = ""
        icon = ""
        url = "/#about"
    # Customize link of author avatar in sidebar
    # [params.sidebar.profile]
    #   url = "/#about"

    # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
    # [params.footer]
    #   copyright = "<a href=\"https://github.com/yumatsuoka\">yumatsuoka</a>"
    # Fonts settings. #robust
    #googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
    #fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
    #logofontfamily = "Lobster, cursive" # Optional, Override logo font.


#[params.author]#robust
#  thumbnail = "source/assets/images/bio-photo.jpg"
#  name = "Yuma Matsuoka"
#  description = "ボルチモアのジョンズホプキンス大学で研究しつつ、クライミングやボルダリングをする日々"
#  github = "https://github.com/yumatsuoka"

[outputs]
page = [ "HTML", "AMP" ] #robust

# Menu Configuration #tranquilpeak
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
#[[menu.main]]
#  weight = 3
#  identifier = "tags"
#  name = "Tags"
#  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
#  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/#about"
[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/yumatsuoka"
[[menu.links]]
  weight = 1
  identifier = "instagram"
  name = "instagram"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-instagram\"></i>"
  url = "https://www.instagram.com/yumatsuge/"
[[menu.misc]]
  weight = 1
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

